#!/bin/sh
cd ${0%/*} || exit 1
. $WM_PROJECT_DIR/bin/tools/RunFunctions
./preprocess
decomposePar
solver=$(getApplication)
mpirun -np $(getNumberOfProcessors) $solver -parallel 2>&1 | tee log.$solver
